micronaut:
  application:
    name: micronaut-dummy
  server:
    port: ${SERVER_PORT:8080}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
tracing:
  zipkin:
    http:
      url: ${ZIPKIN_URL:http://localhost:9411}
    enabled: true
    sampler:
      probability: 1
endpoints:
  prometheus:
    sensitive: false
