apiVersion: v1
kind: Service
metadata:
  name: micronaut-dummy-service
spec:
  type: NodePort
  selector:
    app: micronaut-dummy
  ports:
    - name: http-dummy-service
      protocol: TCP
      port: 80
      targetPort: http-dummy
