name: Build and publish container

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build
        run: ./gradlew build

      - name: Start session
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate container
        run: ./gradlew jib --image=ghcr.io/nombre-repositorio/nombre-contenedor:${{ github.sha }}

      - name: Close session
        uses: docker/logout-action@v1
