name: Build and publish container

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/gradle-build-action@v2
      - name: Generate and publish image with Jib
        run: ./gradlew jib --image=ghcr.io/${{ github.repository }}:${{ github.sha }}
