name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build --no-daemon
