name: Create release tag

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  update-changelog-and-version:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Git user
        run: |
          git config user.email "<>"
          git config user.name "${{ env.CI_COMMIT_AUTHOR }}"
      - name: Install dependencies
        run: npm install
      - name: Run release script
        run: npm run release
      - name: Push changes
        run: git push origin --tags
