name: Release on PR Open

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Git user
        run: |
          git config user.email "scarrionv@gmail.com"
          git config user.name "Santiago Carrión"
      - name: Install dependencies
        run: npm install
      - name: Run release script
        run: npm run release
      - name: Push changes
        run: git push origin HEAD:develop
